<legend class="legend">
    <span><?php echo __('Product Dimensions') ?></span>
</legend>
<div class="field">
    <label class="label"><?php echo __('Length(cm)') ?></label>
    <div class="control">
        <input type="text" data-bind="afterRender:ko.moneyPointMask" name="product[product_length]" class="input-text validate-zero-or-greater" />
    </div>
    <div class="admin__field-note">
        <span><?php echo __('Length of product packaging (For freight calculation, minimum of 16cm') ?></span>
    </div>
</div>
<div class="field">
    <label class="label"><?php echo __('Width(cm)') ?></label>
    <div class="control">
        <input type="text" data-bind="afterRender:ko.moneyPointMask" name="product[product_width]" class="input-text validate-zero-or-greater" />
    </div>
    <div class="admin__field-note">
        <span><?php echo __('Width of product packaging (For freight calculation, minimum of 11cm') ?></span>
    </div>
</div>
<div class="field">
    <label class="label"><?php echo __('Height(cm)') ?></label>
    <div class="control">
        <input type="text" data-bind="afterRender:ko.moneyPointMask" name="product[product_height]" class="input-text validate-zero-or-greater" />
    </div>
    <div class="admin__field-note">
        <span><?php echo __('Width of product packaging (For freight calculation, minimum of 2cm') ?></span>
    </div>
</div>
<div class="field">
    <label class="label"><?php echo __(' Fragile Product') ?></label>
    <div class="control">
        <select name="product[fragile]" class="validate-select validate-zero-or-greater">
            <option value="0"><?php echo __('No') ?></option>
            <option value="1"><?php echo __('Yes') ?></option>
        </select>
    </div>
    <div class="admin__field-note" >
        <span><?php echo __('Does product contain glass or other fragile materials? (For freight calculation)') ?></span>
    </div>
</div>
